apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: go-k8s-microservice
  labels:
    app: go-k8s-microservice
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 1
  template:
    metadata:
      labels:
        app: go-k8s-microservice
    spec:
      containers:
      - name: go-k8s-microservice
        image: docker.io/abdujabbor1987/go-k8s-microservice:0.0.4
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8000
        resources:
          limits:
            cpu: 10m
            memory: 30Mi
          requests:
            cpu: 10m
            memory: 30Mi
      terminationGracePeriodSeconds: 30
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/rewrite-target: /
  labels:
    app: go-k8s-microservice
  name: go-k8s-microservice
spec:
  backend:
    serviceName: go-k8s-microservice
    servicePort: 80
  rules:
  - host: go-microservice.test
    http:
      paths:
      - path: /
        backend:
          serviceName: go-k8s-microservice
          servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: go-k8s-microservice
  labels:
    app: go-k8s-microservice
spec:
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: go-k8s-microservice
---
